version: '3'
services:

  fastapi:
    container_name: fastapi_local
    build:
      context: ./fastapi-app
    volumes:
      - ./fastapi-app:/app
    ports:
      - "8000:8000"
    restart: on-failure

  mongo:
    image: mongo
    container_name: mongo_local
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - './db_dump:/db_dump'